#!/bin/bash -ex

exec docker run --rm --privileged -it -p15306:15306 -e VITESS_COMMIT="${1:-master}" -e MYSQL_DIALECT="${2:-mysql57}" -e VT_KEYSPACES="${3:-test:1:0}" gcr.io/planetscale-vitess-testing/vitess-builder

