#!/bin/bash -ex
function contains() {
	echo "--- 1 = '$1'"
	echo "--- 2 = '$2'"
	[[ $1 =~ (^|[[:space:]])$2($|[[:space:]]) ]] && return 0 || return 1
}

if [ "${RUN_DOCKER}" -eq 1 ]; then
	/usr/local/bin/dockerd-entrypoint.sh --storage-driver=overlay2 &>/dev/null &
fi;

declare -A mysql_versions
mysql_versions[mysql57]=5.7.9-Vitess
mysql_versions[mysql80]=8.0.23-Vitess
dialect_names="${!mysql_versions[@]}";

echo "--- MYSQL_DIALECT = '${MYSQL_DIALECT}'"
if ! contains "${dialect_names}" "${MYSQL_DIALECT}"; then
	echo "!!! Unknown MYSQL_DIALECT '${MYSQL_DIALECT}'";
	exit 1;
fi

git clone -b "${VITESS_COMMIT}" https://github.com/planetscale/vitess.git
cd vitess/examples/compose
go run ./vtcompose -keyspaceData "${VT_KEYSPACES}"
/src/patch-compose docker-compose.yml
cd ../..
patch -p1 < ../docker-compose.patch

# Docker takes a while to start, and sometimes the `git clone` step goes by quickly.  Make sure it's up and ready to go before we proceed.
until docker ps; do sleep 1; done

make "docker_lite_${MYSQL_DIALECT}"
cd ..
sed -i "s/:latest/:${MYSQL_DIALECT}/" Dockerfile
cat Dockerfile
docker build -t "vitess/lite:${MYSQL_DIALECT}-withhacks" .

cp -vf vitess/examples/compose/template.env .env
echo "VITESS_TAG=${MYSQL_DIALECT}-withhacks" >> .env
echo "MYSQL_SERVER_VERSION=${mysql_versions[${MYSQL_DIALECT}]}" >> .env
cp -vf .env vitess/examples/compose/.env
# For whatever reason, this fails after ten seconds even with -t 60
docker-compose -f vitess/examples/compose/docker-compose.yml up || true
docker ps -a
sleep 20
docker ps -a
docker-compose -f vitess/examples/compose/docker-compose.yml up -t 60

