name: Build the builder image
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: build
        name: Build image
        run: docker build -t gcr.io/planetscale-vitess-testing/vitess-builder .
      - id: push
        name: Push image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker push gcr.io/planetscale-vitess-testing/vitess-builder

